import { Exercise, WorkoutType } from '../types';

const DEFAULT_STRENGTH_CURVE = { stretch: 50, mid: 50, contracted: 50 };
const DEFAULT_CUES = [{ icon: '⚡', text: 'Maintain Form' }];

const RAW_EXERCISES = [
  // Upper Body A (Mechanical Tension)
  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    category: 'Chest',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front Delts', 'Triceps'],
    muscleHeads: ['Mid/Lower Chest'],
    targetMuscles: ['Pectoralis Major', 'Triceps', 'Front Deltoid'],
    description: 'The foundational horizontal push for upper body mass.',
    formWarning: 'Maintain scapular retraction and a slight arch to protect the shoulder capsule.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    cues: [
      { icon: '🛡️', text: 'Lock Scapulae' },
      { icon: '📐', text: '45° Elbow Tuck' },
      { icon: '⚡', text: 'Explosive Concentric Force' }
    ],
    strengthCurve: { stretch: 90, mid: 60, contracted: 30 },
    skeletalOverlay: 'Shoulder Girdle',
    lastRotated: '2026-03-01T00:00:00Z',
    keywords: ['chest', 'pecs', 'pectoralis major', 'sternal head', 'push', 'horizontal push', 'barbell']
  },
  {
    id: 'incline-db-press',
    name: 'Incline DB Press',
    category: 'Chest',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front Delts', 'Triceps'],
    muscleHeads: ['Upper Chest'],
    targetMuscles: ['Upper Pectoralis Major'],
    description: 'Upper chest focus with dumbbells.',
    formWarning: 'Slow negative. Continuous time under tension.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    cues: [
      { icon: '📐', text: '45° Tuck' },
      { icon: '📉', text: 'Slow Negative' },
      { icon: '🔥', text: 'Continuous Tension' }
    ],
    strengthCurve: { stretch: 80, mid: 60, contracted: 40 },
    skeletalOverlay: 'Shoulder Girdle',
    lastRotated: '2026-03-20T00:00:00Z',
    keywords: ['chest', 'upper chest', 'pecs', 'clavicular head', 'incline', 'push', 'dumbbells']
  },
  {
    id: 'weighted-pullups',
    name: 'Weighted Pull-ups',
    category: 'Back',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps', 'Abs'],
    muscleHeads: ['Lats'],
    targetMuscles: ['Latissimus Dorsi', 'Biceps', 'Rhomboids'],
    description: 'Vertical pull for back width and strength.',
    formWarning: 'Full range of motion. Chest to bar.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Advanced',
    equipment: 'Bodyweight + Weight',
    cues: [
      { icon: '🦅', text: 'Chest to Bar' },
      { icon: '⬇️', text: 'Depress Shoulders' },
      { icon: '✊', text: 'Full ROM' }
    ],
    strengthCurve: { stretch: 30, mid: 70, contracted: 100 },
    skeletalOverlay: 'Shoulder Girdle',
    lastRotated: '2026-03-05T00:00:00Z',
    keywords: ['back', 'lats', 'latissimus dorsi', 'pull', 'vertical pull', 'width', 'pullups']
  },
  {
    id: 'rdl',
    name: 'Romanian Deadlift',
    category: 'Legs',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes', 'Abs'],
    muscleHeads: ['Hamstrings'],
    targetMuscles: ['Hamstrings', 'Gluteus Maximus', 'Erector Spinae'],
    description: 'Hinge movement for posterior chain.',
    formWarning: 'Hinge at hips. Neutral cervical spine.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    cues: [
      { icon: '🍑', text: 'Hinge at Hips' },
      { icon: '📏', text: 'Neutral Cervical Spine' },
      { icon: '🧘', text: 'Feel the Stretch' }
    ],
    strengthCurve: { stretch: 100, mid: 50, contracted: 10 },
    skeletalOverlay: 'Spine Alignment',
    lastRotated: '2026-03-01T00:00:00Z',
    keywords: ['legs', 'hamstrings', 'biceps femoris', 'posterior chain', 'hinge', 'rdl']
  },
  {
    id: 'leg-extensions',
    name: 'Leg Extensions',
    category: 'Legs',
    primaryMuscles: ['Quads'],
    secondaryMuscles: [],
    muscleHeads: ['Outer Quad'],
    targetMuscles: ['Quadriceps'],
    description: 'Isolation for quad definition.',
    formWarning: '15-20 Reps. Extreme metabolic burn.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Beginner',
    equipment: 'Leg Extension Machine',
    cues: [
      { icon: '✊', text: 'Peak Squeeze' },
      { icon: '🔥', text: 'Extreme Burn' },
      { icon: '🔢', text: '15-20 Reps' }
    ],
    strengthCurve: { stretch: 20, mid: 60, contracted: 100 },
    skeletalOverlay: 'None',
    lastRotated: '2026-03-25T00:00:00Z',
    keywords: ['legs', 'quads', 'quadriceps', 'vastus lateralis', 'isolation', 'extensions']
  },
  {
    id: 'overhead-press',
    name: 'Overhead Barbell Press',
    category: 'Shoulders',
    primaryMuscles: ['Front Delts'],
    secondaryMuscles: ['Triceps', 'Abs'],
    targetMuscles: ['Front Deltoid', 'Triceps', 'Upper Trapezius'],
    description: 'Strict press for shoulder power.',
    formWarning: 'Brace core. Do not arch lower back.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    muscleHeads: ['Front Shoulder'],
    cues: [{ icon: '🧱', text: 'Brace Core' }],
    strengthCurve: { stretch: 100, mid: 60, contracted: 40 },
    skeletalOverlay: 'Shoulder Girdle' as const,
    keywords: ['shoulders', 'delts', 'front delts', 'anterior deltoid', 'press', 'overhead press', 'ohp']
  },
  {
    id: 'barbell-rows',
    name: 'Barbell Rows',
    category: 'Back',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps', 'Abs'],
    targetMuscles: ['Rhomboids', 'Trapezius', 'Latissimus Dorsi'],
    description: 'Horizontal pull for back thickness.',
    formWarning: 'Maintain flat back. Pull to upper waist.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    muscleHeads: ['Lats', 'Upper Back'],
    cues: [{ icon: '🚣', text: 'Pull to Waist' }],
    strengthCurve: { stretch: 40, mid: 80, contracted: 100 },
    keywords: ['back', 'lats', 'rhomboids', 'traps', 'thickness', 'rows', 'barbell rows']
  },
  {
    id: 'heavy-barbell-curls',
    name: 'Heavy Barbell Curls',
    category: 'Arms',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Abs'],
    targetMuscles: ['Biceps Brachii'],
    description: 'Strict curls for bicep strength.',
    formWarning: 'No swinging. Full extension.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Beginner',
    equipment: 'Barbell',
    muscleHeads: ['Biceps'],
    cues: [{ icon: '🚫', text: 'No Swinging' }],
    strengthCurve: { stretch: 20, mid: 100, contracted: 80 },
    keywords: ['arms', 'biceps', 'biceps brachii', 'curls', 'barbell curls']
  },
  {
    id: 'skullcrushers',
    name: 'EZ-Bar Skullcrushers',
    category: 'Arms',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Abs'],
    targetMuscles: ['Triceps Brachii'],
    description: 'Isolation for tricep power.',
    formWarning: 'Keep elbows fixed. Lower to forehead.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'EZ-Bar',
    muscleHeads: ['Inner Triceps'],
    cues: [{ icon: '🧱', text: 'Fixed Elbows' }],
    strengthCurve: { stretch: 100, mid: 60, contracted: 20 },
    keywords: ['arms', 'triceps', 'triceps brachii', 'skullcrushers', 'isolation']
  },
  {
    id: 'squat',
    name: 'High Bar Back Squat',
    category: 'Legs',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes', 'Abs'],
    targetMuscles: ['Quadriceps', 'Gluteus Maximus', 'Adductors'],
    description: 'Fundamental lower body compound lift.',
    formWarning: 'Maintain neutral spine. Drive through mid-foot.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Advanced',
    equipment: 'Barbell',
    muscleHeads: ['Inner Quad', 'Outer Quad'],
    cues: [{ icon: '🌪️', text: 'Screw Feet in' }],
    strengthCurve: { stretch: 100, mid: 70, contracted: 20 },
    keywords: ['legs', 'quads', 'quadriceps', 'glutes', 'squats', 'compound']
  },
  {
    id: 'standing-calf-raise',
    name: 'Standing Calf Raise',
    category: 'Legs',
    primaryMuscles: ['Calves'],
    secondaryMuscles: [],
    targetMuscles: ['Gastrocnemius'],
    description: 'Heavy calf isolation.',
    formWarning: 'Full stretch at bottom. Peak contraction.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Beginner',
    equipment: 'Calf Machine',
    muscleHeads: ['Calves'],
    cues: [{ icon: '🧘', text: 'Deep Stretch' }],
    strengthCurve: { stretch: 100, mid: 60, contracted: 80 },
    keywords: ['legs', 'calves', 'gastrocnemius', 'isolation', 'calf raise']
  },
  {
    id: 'weighted-plank',
    name: 'Weighted Plank',
    category: 'Core',
    primaryMuscles: ['Abs'],
    secondaryMuscles: ['Glutes'],
    targetMuscles: ['Rectus Abdominis', 'Obliques'],
    description: 'Isometric core stability.',
    formWarning: 'Maintain hollow body position. Do not sag hips.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Intermediate',
    equipment: 'Weight Plate',
    muscleHeads: ['Abs'],
    cues: [{ icon: '🧱', text: 'Hollow Body' }],
    strengthCurve: { stretch: 0, mid: 100, contracted: 0 },
    keywords: ['core', 'abs', 'rectus abdominis', 'stability', 'plank']
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    category: 'Shoulders',
    primaryMuscles: ['Lateral Delts'],
    secondaryMuscles: ['Front Delts'],
    targetMuscles: ['Lateral Deltoid'],
    description: 'Isolation for side delts.',
    formWarning: 'Lead with elbows. Do not shrug.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    muscleHeads: ['Side Shoulder'],
    cues: [{ icon: '🦅', text: 'Lead with Elbows' }],
    strengthCurve: { stretch: 10, mid: 60, contracted: 100 },
    keywords: ['shoulders', 'delts', 'lateral delts', 'middle deltoid', 'isolation', 'width']
  },
  {
    id: 'cable-rows',
    name: 'Seated Cable Rows',
    category: 'Back',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    targetMuscles: ['Latissimus Dorsi', 'Rhomboids'],
    description: 'Controlled horizontal pull.',
    formWarning: 'Keep torso upright. Squeeze shoulder blades.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    muscleHeads: ['Lats'],
    cues: [{ icon: '✊', text: 'Squeeze Blades' }],
    strengthCurve: { stretch: 40, mid: 80, contracted: 100 },
    keywords: ['back', 'lats', 'rhomboids', 'rows', 'cable rows', 'thickness']
  },
  {
    id: 'leg-curls',
    name: 'Seated Leg Curls',
    category: 'Legs',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: [],
    targetMuscles: ['Hamstrings'],
    description: 'Isolation for hamstring mass.',
    formWarning: 'Do not lift hips off seat.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Beginner',
    equipment: 'Leg Curl Machine',
    muscleHeads: ['Hamstrings'],
    cues: [{ icon: '🧱', text: 'Hips Down' }],
    strengthCurve: { stretch: 30, mid: 70, contracted: 100 },
    keywords: ['legs', 'hamstrings', 'isolation', 'leg curls']
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    category: 'Legs',
    primaryMuscles: ['Calves'],
    secondaryMuscles: [],
    targetMuscles: ['Soleus'],
    description: 'Isolation for lower calf.',
    formWarning: 'Full range of motion.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Beginner',
    equipment: 'Seated Calf Machine',
    muscleHeads: ['Lower Calves'],
    cues: [{ icon: '🧘', text: 'Deep Stretch' }],
    strengthCurve: { stretch: 100, mid: 60, contracted: 80 },
    keywords: ['legs', 'calves', 'soleus', 'isolation', 'calf raise']
  },
  {
    id: 'hanging-leg-raises',
    name: 'Hanging Leg Raises',
    category: 'Core',
    primaryMuscles: ['Abs'],
    secondaryMuscles: [],
    targetMuscles: ['Rectus Abdominis'],
    description: 'Advanced core isolation.',
    formWarning: 'Avoid swinging. Control the descent.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Advanced',
    equipment: 'Pull-up Bar',
    muscleHeads: ['Abs'],
    cues: [{ icon: '🚫', text: 'No Swinging' }],
    strengthCurve: { stretch: 20, mid: 60, contracted: 100 },
    keywords: ['core', 'abs', 'rectus abdominis', 'hanging', 'leg raises']
  },
  {
    id: 'deadlift',
    name: 'Conventional Deadlift',
    category: 'Legs',
    primaryMuscles: ['Hamstrings'],
    secondaryMuscles: ['Glutes', 'Abs'],
    targetMuscles: ['Erector Spinae', 'Hamstrings', 'Gluteus Maximus'],
    description: 'The ultimate posterior chain lift.',
    formWarning: 'Flat back. Pull slack out of bar.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Advanced',
    equipment: 'Barbell',
    muscleHeads: ['Hamstrings', 'Lower Back'],
    cues: [{ icon: '🧱', text: 'Flat Back' }],
    strengthCurve: { stretch: 100, mid: 80, contracted: 40 },
    keywords: ['legs', 'back', 'hamstrings', 'glutes', 'erector spinae', 'deadlift', 'compound']
  },
  {
    id: 'dips',
    name: 'Weighted Dips',
    category: 'Chest',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Triceps', 'Front Delts'],
    muscleHeads: ['Lower Chest'],
    targetMuscles: ['Lower Pectoralis Major', 'Triceps Brachii'],
    description: 'Vertical push for chest and triceps.',
    formWarning: 'Lean forward for chest focus.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Dip Bars',
    cues: [{ icon: '🦅', text: 'Lean Forward' }],
    strengthCurve: { stretch: 100, mid: 60, contracted: 20 },
    keywords: ['chest', 'triceps', 'front delts', 'pecs', 'dips', 'push']
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'Back',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps'],
    targetMuscles: ['Latissimus Dorsi'],
    description: 'Vertical pull for width.',
    formWarning: 'Pull to upper chest.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    muscleHeads: ['Lats'],
    cues: [{ icon: '🦅', text: 'Chest Up' }],
    strengthCurve: { stretch: 30, mid: 70, contracted: 100 },
    keywords: ['back', 'lats', 'latissimus dorsi', 'pull', 'vertical pull', 'width', 'pulldown']
  },
  {
    id: 'face-pulls',
    name: 'Face Pulls',
    category: 'Shoulders',
    primaryMuscles: ['Rear Delts'],
    secondaryMuscles: ['Traps'],
    targetMuscles: ['Rear Deltoid', 'Trapezius'],
    description: 'Isolation for rear delts and posture.',
    formWarning: 'Pull to forehead. Squeeze rear delts.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    muscleHeads: ['Rear Shoulder'],
    cues: [{ icon: '✊', text: 'Squeeze Rear' }],
    strengthCurve: { stretch: 20, mid: 60, contracted: 100 },
    keywords: ['shoulders', 'rear delts', 'posterior deltoid', 'traps', 'face pulls', 'isolation']
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    category: 'Legs',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes'],
    targetMuscles: ['Quadriceps'],
    description: 'Machine squat for quad isolation.',
    formWarning: 'Full depth. Keep back against pad.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Intermediate',
    equipment: 'Hack Squat Machine',
    muscleHeads: ['Outer Quad'],
    cues: [{ icon: '🧱', text: 'Back Flat' }],
    strengthCurve: { stretch: 100, mid: 70, contracted: 20 },
    keywords: ['legs', 'quads', 'quadriceps', 'glutes', 'hack squat', 'machine']
  },
  {
    id: 'cable-flyes-low-to-high',
    name: 'Cable Flyes (Low-to-High)',
    category: 'Chest',
    primaryMuscles: ['Chest'],
    secondaryMuscles: ['Front Delts'],
    muscleHeads: ['Upper Chest'],
    targetMuscles: ['Upper Pectoralis Major'],
    description: 'Isolation for upper chest peak contraction.',
    formWarning: 'Maintain slight elbow bend. Squeeze at the top.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Cable Machine',
    cues: [{ icon: '✊', text: 'Peak Squeeze' }],
    strengthCurve: { stretch: 40, mid: 70, contracted: 100 },
    keywords: ['chest', 'upper chest', 'pecs', 'clavicular head', 'flyes', 'cable flyes']
  },
  {
    id: 'db-shrugs',
    name: 'Dumbbell Shrugs',
    category: 'Shoulders',
    primaryMuscles: ['Traps'],
    secondaryMuscles: ['Shoulders'],
    targetMuscles: ['Upper Trapezius'],
    description: 'Isolation for upper traps.',
    formWarning: 'Do not roll shoulders. Straight up and down.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    muscleHeads: ['Upper Traps'],
    cues: [{ icon: '🦒', text: 'Straight Up' }],
    strengthCurve: { stretch: 60, mid: 80, contracted: 100 },
    keywords: ['shoulders', 'traps', 'upper trapezius', 'shrugs', 'isolation']
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curls',
    category: 'Arms',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: [],
    muscleHeads: ['Inner Biceps'],
    targetMuscles: ['Biceps Brachii'],
    description: 'Isolation for bicep peak and short head.',
    formWarning: 'Full extension at the bottom. Do not bounce.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Preacher Bench',
    cues: [{ icon: '🧘', text: 'Full Extension' }],
    strengthCurve: { stretch: 100, mid: 60, contracted: 20 },
    keywords: ['arms', 'biceps', 'biceps brachii', 'short head', 'peak', 'preacher curls']
  },
  {
    id: 'rope-pushdowns',
    name: 'Rope Pushdowns',
    category: 'Arms',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    muscleHeads: ['Outer Triceps'],
    targetMuscles: ['Triceps Brachii'],
    description: 'Isolation for tricep lateral head.',
    formWarning: 'Spread the rope at the bottom.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Beginner',
    equipment: 'Cable Machine',
    cues: [{ icon: '↔️', text: 'Spread Rope' }],
    strengthCurve: { stretch: 20, mid: 60, contracted: 100 },
    keywords: ['arms', 'triceps', 'triceps brachii', 'lateral head', 'pushdowns', 'cable pushdowns']
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curls',
    category: 'Arms',
    primaryMuscles: ['Biceps'],
    secondaryMuscles: ['Forearms'],
    targetMuscles: ['Brachialis', 'Brachioradialis'],
    description: 'Neutral grip for brachialis thickness.',
    formWarning: 'Keep elbows fixed at sides.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Beginner',
    equipment: 'Dumbbells',
    muscleHeads: ['Side Biceps', 'Forearm'],
    cues: [{ icon: '🔨', text: 'Neutral Grip' }],
    strengthCurve: { stretch: 30, mid: 100, contracted: 70 },
    keywords: ['arms', 'biceps', 'brachialis', 'brachioradialis', 'forearms', 'hammer curls']
  },
  {
    id: 'close-grip-bench',
    name: 'Close Grip Bench Press',
    category: 'Arms',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: ['Chest', 'Front Delts'],
    muscleHeads: ['Inner Triceps', 'Outer Triceps'],
    targetMuscles: ['Triceps Brachii', 'Pectoralis Major'],
    description: 'Heavy horizontal push focusing on triceps mass.',
    formWarning: 'Keep elbows tucked. Do not go too narrow to protect wrists.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Barbell',
    cues: [{ icon: '📐', text: 'Elbows Tucked' }, { icon: '🧱', text: 'Brace Core' }],
    strengthCurve: { stretch: 80, mid: 60, contracted: 40 },
    keywords: ['arms', 'triceps', 'push', 'bench press', 'close grip']
  },
  {
    id: 'overhead-cable-extension',
    name: 'Overhead Cable Extension',
    category: 'Arms',
    primaryMuscles: ['Triceps'],
    secondaryMuscles: [],
    muscleHeads: ['Inner Triceps'],
    targetMuscles: ['Triceps Brachii (Long Head)'],
    description: 'Isolation for the long head of the triceps in the stretched position.',
    formWarning: 'Maintain a stable torso. Do not arch lower back.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Cable Machine',
    cues: [{ icon: '🧘', text: 'Deep Stretch' }, { icon: '🧱', text: 'Stable Core' }],
    strengthCurve: { stretch: 100, mid: 60, contracted: 20 },
    keywords: ['arms', 'triceps', 'long head', 'overhead', 'cable', 'isolation']
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'Legs',
    primaryMuscles: ['Quads'],
    secondaryMuscles: ['Glutes', 'Abs'],
    muscleHeads: ['Inner Quad', 'Outer Quad'],
    targetMuscles: ['Quadriceps', 'Gluteus Maximus'],
    description: 'Unilateral movement for leg mass and stability.',
    formWarning: 'Keep front knee aligned with toes. Maintain upright torso.',
    type: 'Mechanical Tension' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Advanced',
    equipment: 'Dumbbells',
    cues: [{ icon: '⚖️', text: 'Balance Core' }, { icon: '📐', text: 'Knee Alignment' }],
    strengthCurve: { stretch: 100, mid: 70, contracted: 30 },
    keywords: ['legs', 'quads', 'glutes', 'unilateral', 'split squat']
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunches',
    category: 'Core',
    primaryMuscles: ['Abs'],
    secondaryMuscles: [],
    muscleHeads: ['Abs'],
    targetMuscles: ['Rectus Abdominis'],
    description: 'Weighted isolation for ab thickness.',
    formWarning: 'Crunch with your abs, not your hips. Exhale at the bottom.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Lower',
    difficulty: 'Intermediate',
    equipment: 'Cable Machine',
    cues: [{ icon: '🐚', text: 'Curl Spine' }, { icon: '💨', text: 'Exhale on Squeeze' }],
    strengthCurve: { stretch: 20, mid: 60, contracted: 100 },
    keywords: ['core', 'abs', 'rectus abdominis', 'weighted abs', 'cable crunch']
  },
  {
    id: 'single-arm-db-row',
    name: 'Single Arm DB Row',
    category: 'Back',
    primaryMuscles: ['Lats'],
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    muscleHeads: ['Lats', 'Upper Back'],
    targetMuscles: ['Latissimus Dorsi', 'Rhomboids', 'Rear Deltoid'],
    description: 'Unilateral horizontal pull for back detail.',
    formWarning: 'Do not rotate torso. Pull elbow to hip.',
    type: 'Metabolic Stress' as WorkoutType,
    splitCategory: 'Upper',
    difficulty: 'Intermediate',
    equipment: 'Dumbbells',
    cues: [{ icon: '🏹', text: 'Elbow to Hip' }, { icon: '🚫', text: 'No Rotation' }],
    strengthCurve: { stretch: 60, mid: 80, contracted: 100 },
    keywords: ['back', 'lats', 'rows', 'unilateral', 'dumbbells']
  }
];

export const EXERCISES: Exercise[] = RAW_EXERCISES.map(ex => ({
  ...ex,
  primaryMuscles: ex.primaryMuscles || [],
  secondaryMuscles: ex.secondaryMuscles || [],
  difficulty: ex.difficulty || 'Intermediate',
  equipment: ex.equipment || 'None',
  cues: ex.cues || DEFAULT_CUES,
  strengthCurve: ex.strengthCurve || DEFAULT_STRENGTH_CURVE
})) as Exercise[];
