export const foodDatabase = [
  { name: "Paneer (Low Fat)", unit: "100g", protein: 18, calories: 265 },
  { name: "Soya Chunks (Boiled)", unit: "100g", protein: 52, calories: 345 },
  { name: "Moong Dal (Cooked)", unit: "1 Cup", protein: 14, calories: 212 },
  { name: "Chana (Chickpeas)", unit: "1 Cup", protein: 15, calories: 269 },
  { name: "Rajma (Kidney Beans)", unit: "1 Cup", protein: 15, calories: 225 },
  { name: "Masoor Dal (Lentils)", unit: "1 Cup", protein: 18, calories: 230 },
  { name: "Greek Yogurt (Plain)", unit: "1 Cup", protein: 17, calories: 100 },
  { name: "Sattu (Gram Flour)", unit: "100g", protein: 20, calories: 360 },
  { name: "Tofu (Extra Firm)", unit: "100g", protein: 12, calories: 90 },
  { name: "Milk (Full Cream)", unit: "1 Cup", protein: 8, calories: 150 },
  { name: "Milk (Skimmed)", unit: "1 Cup", protein: 8, calories: 90 },
  { name: "Curd (Dahi)", unit: "1 Cup", protein: 10, calories: 120 },
  { name: "Buttermilk (Chaas)", unit: "1 Glass", protein: 3, calories: 40 },
  { name: "Peanuts (Roasted)", unit: "1 Handful", protein: 7, calories: 160 },
  { name: "Almonds", unit: "10 Items", protein: 3, calories: 70 },
  { name: "Walnuts", unit: "5 Items", protein: 2, calories: 130 },
  { name: "Cashews", unit: "10 Items", protein: 5, calories: 150 },
  { name: "Pistachios", unit: "20 Items", protein: 6, calories: 160 },
  { name: "Chia Seeds", unit: "2 Tbsp", protein: 5, calories: 138 },
  { name: "Flax Seeds", unit: "2 Tbsp", protein: 4, calories: 110 },
  { name: "Whole Egg (Large)", unit: "1 Item", protein: 6, calories: 78 },
  { name: "Egg White", unit: "1 Item", protein: 3.6, calories: 17 },
  { name: "Chicken Breast (Boiled)", unit: "100g", protein: 31, calories: 165 },
  { name: "Chicken Thigh (Skinless)", unit: "100g", protein: 24, calories: 210 },
  { name: "Fish (Rohu/Katla)", unit: "100g", protein: 17, calories: 100 },
  { name: "Fish (Pomfret)", unit: "100g", protein: 19, calories: 120 },
  { name: "Salmon Fillet", unit: "100g", protein: 22, calories: 208 },
  { name: "Tuna (Canned in Water)", unit: "100g", protein: 25, calories: 116 },
  { name: "Shrimp (Prawns)", unit: "100g", protein: 24, calories: 99 },
  { name: "Lean Mutton (Goat)", unit: "100g", protein: 25, calories: 250 },
  { name: "Lean Beef", unit: "100g", protein: 26, calories: 250 },
  { name: "Turkey Breast", unit: "100g", protein: 29, calories: 135 },
  { name: "Bacon (Turkey)", unit: "2 Slices", protein: 6, calories: 70 },
  { name: "White Rice (Cooked)", unit: "1 Cup", protein: 4, calories: 205 },
  { name: "Brown Rice (Cooked)", unit: "1 Cup", protein: 5, calories: 218 },
  { name: "Oatmeal (Raw)", unit: "1 Cup", protein: 11, calories: 300 },
  { name: "Quinoa (Cooked)", unit: "1 Cup", protein: 8, calories: 222 },
  { name: "Sweet Potato", unit: "1 Medium", protein: 2, calories: 103 },
  { name: "Potato (Boiled)", unit: "1 Medium", protein: 3, calories: 110 },
  { name: "Chapati (Whole Wheat)", unit: "1 Item", protein: 3, calories: 70 },
  { name: "Multi-grain Bread", unit: "1 Slice", protein: 4, calories: 80 },
  { name: "Banana", unit: "1 Medium", protein: 1.3, calories: 105 },
  { name: "Pasta (Whole Wheat)", unit: "1 Cup", protein: 8, calories: 180 },
  { name: "Whey Protein Isolate", unit: "1 Scoop", protein: 25, calories: 110 },
  { name: "Whey Protein Blend", unit: "1 Scoop", protein: 24, calories: 130 },
  { name: "Casein Protein", unit: "1 Scoop", protein: 24, calories: 110 },
  { name: "Protein Bar (Standard)", unit: "1 Bar", protein: 20, calories: 220 },
  { name: "Peanut Butter", unit: "1 Tbsp", protein: 4, calories: 95 },
  { name: "Almond Butter", unit: "1 Tbsp", protein: 3.5, calories: 98 },
  { name: "Skyr (Icelandic Yogurt)", unit: "170g", protein: 19, calories: 110 },
  { name: "Seitan (Wheat Gluten)", unit: "100g", protein: 25, calories: 140 },
  { name: "Tempeh", unit: "100g", protein: 19, calories: 190 },
  { name: "Beef Jerky", unit: "28g", protein: 9, calories: 80 },
  { name: "Avocado", unit: "1 Medium", protein: 3, calories: 322 },
  { name: "Spinach (Cooked)", unit: "1 Cup", protein: 5, calories: 41 },
  { name: "Broccoli", unit: "1 Cup", protein: 2.5, calories: 31 },
  { name: "Pumpkin Seeds", unit: "1 oz", protein: 9, calories: 160 },
  { name: "Sunflower Seeds", unit: "1 oz", protein: 6, calories: 165 },
  { name: "Hummus", unit: "2 Tbsp", protein: 2, calories: 70 },
  { name: "Olive Oil", unit: "1 Tbsp", protein: 0, calories: 120 },
  { name: "Honey", unit: "1 Tbsp", protein: 0, calories: 60 },
  { name: "Dark Chocolate (85%)", unit: "1 Square", protein: 1, calories: 60 }
];
